CREATE TYPE "Panel" AS ENUM ('DASHBOARD', 'PRODUCTS', 'PURCHASES', 'WASTE', 'RECIPES', 'PRODUCTION', 'INVENTORY', 'AUDIT', 'ORDERS', 'SALES', 'MENU_ENGINEERING', 'SETTINGS');

ALTER TABLE "users" ADD COLUMN "allowedPanels" "Panel"[] NOT NULL DEFAULT ARRAY[]::"Panel"[];
